"""empty message

Revision ID: 09f2276e51a5
Revises: d2e98f0cd413
Create Date: 2024-01-21 00:41:01.477737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f2276e51a5'
down_revision = 'd2e98f0cd413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('salt', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.String(length=200), nullable=False))
        batch_op.drop_column('password')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('nombre')
        batch_op.drop_column('salt')
        batch_op.drop_column('hashed_password')

    # ### end Alembic commands ###
