"""empty message

Revision ID: 6ef9e6510c42
Revises: 267650d7a52d
Create Date: 2024-01-25 01:43:08.451541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef9e6510c42'
down_revision = '267650d7a52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terminos', sa.Boolean(), nullable=False))
        batch_op.drop_column('terminos_y_condiciones')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terminos_y_condiciones', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('terminos')

    # ### end Alembic commands ###
