"""empty message

Revision ID: ddc5b1d79604
Revises: 
Create Date: 2024-01-27 00:54:20.708938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc5b1d79604'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('salt', sa.String(length=250), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.BigInteger(), nullable=True),
    sa.Column('organizacion', sa.String(length=200), nullable=False),
    sa.Column('pagina_web', sa.String(length=500), nullable=False),
    sa.Column('terminos', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=80), nullable=False),
    sa.Column('salt', sa.String(length=250), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('apellido', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('telefono', sa.BigInteger(), nullable=True),
    sa.Column('terminos', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('organizador')
    # ### end Alembic commands ###
